import { writeFileSync } from 'node:fs'

import { checksumHex, clipCachePath, ensureClipCached, manifestClips, type ManifestClip } from '../audio/clip-cache.js'
import { DEFAULT_MFCC_PARAMS, emptyMfccCache, extractMfcc, loadMfccCache, saveMfccCache, type MfccTarget } from '../audio/mfcc.js'
import {
  DEFAULT_ANALYSIS_PARAMS,
  emptyFeaturesCache,
  extractFeatures,
  loadFeaturesCache,
  saveFeaturesCache,
  type FeatureTarget,
} from '../audio/features.js'
import { SEARCH_BANK_VERSION, type SearchBank, type SearchBankClip } from '../audio/search-bank.js'
import { AUDIO_SEARCH_BANK_FILE } from '../paths.js'
import { loadAudio } from '../phonology/load.js'
import { ensureCacheSymlinkOrExit } from './cache-symlink.js'
import { bold, dim, red, green } from './colour.js'

/**
 * `npm run audio:build-search-bank -- [--variety=chaozhou] [--speaker=jky] [--refresh]`
 * (issue #279's web follow-up, extended by #280 to carry WORLD features
 * alongside MFCC)
 *
 * Precomputes MFCC vectors plus `onsetMs`/`f0.contour` for every one of
 * `speaker`'s reference syllable clips and writes them to
 * `data/wordlists/audio-search-bank.json`, keyed by Peng'im syllable rather
 * than by checksum — the web app's speak-to-search feature only needs "which
 * syllable did this match," not the cache-internal detail a checksum key
 * would carry.
 *
 * Committed rather than built in CI: extracting these features needs the
 * corpus (network) and the Python tool, neither available in the offline
 * `npm run build` pipeline or `.github/workflows/deploy.yml` — same
 * reasoning as `data/wordlists/syllable-inventory.yaml`, regenerated by hand
 * via its own command rather than derived automatically on every build.
 *
 * Network-touching (fills `.cache/audio-clips/` for anything not already
 * cached from a prior `audio:grade`/`audio:verify`/`audio:classify` run), so
 * kept out of `npm run check` like every other `audio:*` command. Runs the
 * MFCC and WORLD-features extractors both — independently cached/versioned
 * by design (see `src/audio/mfcc.ts`), so this command touches both caches
 * rather than one.
 */

const USAGE = `usage:
  npm run audio:build-search-bank                       jky/chaozhou, write data/wordlists/audio-search-bank.json
  npm run audio:build-search-bank -- --variety=shantou   a different variety
  npm run audio:build-search-bank -- --speaker=jky       a different reference speaker
  npm run audio:build-search-bank -- --refresh           re-extract MFCC for every reference`

const args = process.argv.slice(2)
if (args.includes('--help') || args.includes('-h')) {
  console.log(USAGE)
  process.exit(0)
}

const variety = args.find((a) => a.startsWith('--variety='))?.slice('--variety='.length) ?? 'chaozhou'
const speaker = args.find((a) => a.startsWith('--speaker='))?.slice('--speaker='.length) ?? 'jky'
const refresh = args.includes('--refresh')

ensureCacheSymlinkOrExit('build-search-bank')

const audio = loadAudio(variety)
const refs = manifestClips(audio).filter((m) => m.clip.speaker === speaker)
if (refs.length === 0) {
  console.error(red(`no clips for speaker '${speaker}' in variety '${variety}'`))
  process.exit(1)
}

console.log(bold(`${variety}: ${refs.length} reference clip${refs.length === 1 ? '' : 's'} (speaker: ${speaker})`))

const isTTY = process.stdout.isTTY
function progress(label: string, every: number): (done: number, total: number) => void {
  return isTTY
    ? (done, total) => process.stdout.write(`\r${dim(`${done}/${total} ${label}`)}`)
    : (done, total) => {
        if (done % every === 0 || done === total) console.log(dim(`${done}/${total} ${label}`))
      }
}
function endProgress(): void {
  if (isTTY) process.stdout.write('\n')
}

const cached: ManifestClip[] = []
const onFetch = progress('cached', 100)
let failures = 0
for (const [i, entry] of refs.entries()) {
  const result = await ensureClipCached(entry.clip)
  if (result.ok) {
    cached.push(entry)
  } else {
    failures += 1
    console.log(`\n  ${red('error')} ${entry.path}: ${result.error}`)
  }
  onFetch(i + 1, refs.length)
}
endProgress()

const mfccCache = (refresh ? null : loadMfccCache()) ?? emptyMfccCache(DEFAULT_MFCC_PARAMS)
const pendingMfcc: MfccTarget[] = cached
  .filter((entry) => refresh || mfccCache.clips[checksumHex(entry.clip.checksum)] === undefined)
  .map((entry) => ({ id: checksumHex(entry.clip.checksum), webmPath: clipCachePath(entry.clip.checksum) }))
if (pendingMfcc.length > 0) {
  console.log(dim(`  extracting MFCC for ${pendingMfcc.length} clip${pendingMfcc.length === 1 ? '' : 's'}…`))
  const result = extractMfcc(pendingMfcc, { params: mfccCache.params, onProgress: progress('analysed', 1) })
  endProgress()
  Object.assign(mfccCache.clips, result.clips)
  for (const [clipId, message] of Object.entries(result.errors)) {
    failures += 1
    console.log(`  ${red('error')} ${clipId}: ${message}`)
  }
  saveMfccCache(mfccCache)
} else {
  console.log(dim('  MFCC already cached for every reference'))
}

const featuresCache = (refresh ? null : loadFeaturesCache()) ?? emptyFeaturesCache(DEFAULT_ANALYSIS_PARAMS)
const pendingFeatures: FeatureTarget[] = cached
  .filter((entry) => refresh || featuresCache.clips[checksumHex(entry.clip.checksum)] === undefined)
  .map((entry) => ({ id: checksumHex(entry.clip.checksum), webmPath: clipCachePath(entry.clip.checksum) }))
if (pendingFeatures.length > 0) {
  console.log(dim(`  extracting WORLD features for ${pendingFeatures.length} clip${pendingFeatures.length === 1 ? '' : 's'}…`))
  const result = extractFeatures(pendingFeatures, { params: featuresCache.params, onProgress: progress('analysed', 1) })
  endProgress()
  Object.assign(featuresCache.clips, result.clips)
  for (const [clipId, message] of Object.entries(result.errors)) {
    failures += 1
    console.log(`  ${red('error')} ${clipId}: ${message}`)
  }
  saveFeaturesCache(featuresCache)
} else {
  console.log(dim('  WORLD features already cached for every reference'))
}

// Round to a shipped precision: the caches keep full precision for internal
// use, but the bank is read-only from here on and every byte is downloaded
// by a browser on first use.
function round3(frames: number[][]): number[][] {
  return frames.map((frame) => frame.map((v) => Math.round(v * 1000) / 1000))
}
function round1(contour: number[]): number[] {
  return contour.map((v) => Math.round(v * 10) / 10)
}

const bankClips: Record<string, SearchBankClip> = {}
for (const entry of cached) {
  const mfcc = mfccCache.clips[checksumHex(entry.clip.checksum)]?.frames
  if (!mfcc) continue
  const features = featuresCache.clips[checksumHex(entry.clip.checksum)]
  bankClips[entry.key] = {
    mfcc: round3(mfcc),
    onsetMs: features?.onsetMs != null ? Math.round(features.onsetMs) : null,
    f0Contour: features?.f0.contour ? round1(features.f0.contour) : null,
  }
}

const bank: SearchBank = {
  version: SEARCH_BANK_VERSION,
  mfccParams: mfccCache.params,
  featuresParams: featuresCache.params,
  speaker,
  variety,
  clips: bankClips,
}
writeFileSync(AUDIO_SEARCH_BANK_FILE, JSON.stringify(bank))
console.log(dim(`  ${Object.keys(bankClips).length} syllables → ${AUDIO_SEARCH_BANK_FILE}`))

if (failures > 0) {
  console.log(red(`\n✗ ${failures} reference clip${failures === 1 ? '' : 's'} could not be fetched or analysed`))
  process.exit(1)
}
console.log(green('\n✓ search bank built'))
