import { mkdirSync, writeFileSync } from 'node:fs'
import { stringify } from 'yaml'

import { SYLLABLE_INVENTORY_FILE, WORDLISTS_DIR } from '../paths.js'
import { buildSyllableInventory } from '../phonology/inventory.js'

/**
 * `npm run inventory` — regenerate data/wordlists/syllable-inventory.yaml
 * (issue #30). Fully offline: reads data/phonology/pengim.yaml, data/entries/,
 * and the cached external chart at data/phonology/external/ (refreshed
 * separately via `npm run xref`, never fetched live here).
 *
 * Unlike data/wordlists/swadesh-207.yaml, this file is not hand-maintained —
 * it is 100% derivable from the inputs above, so it is committed AND checked
 * for staleness by a drift-check test (tests/inventory.test.ts), which is
 * what makes `npm run check` fail if pengim.yaml or an entry's readings
 * change without this command being rerun.
 */

const inventory = buildSyllableInventory()

const onlyShantouChaoyang = inventory.varieties.filter((v) => v !== 'chaozhou')
const unattestedCounts = Object.fromEntries(
  inventory.varieties.map((v) => [
    v,
    inventory.items.filter((i) => i.varieties[v]?.status === 'unattested').length,
  ]),
)

const header = [
  '# The full legal Peng\'im syllable inventory (issue #30), generated by',
  '# `npm run inventory` from data/phonology/pengim.yaml + data/entries/.',
  '#',
  '# Unlike swadesh-207.yaml, this file IS script-regenerated — a stale copy',
  '# fails `npm run check` via the inventory drift-check test. Do not hand-edit;',
  '# rerun `npm run inventory` instead.',
  '#',
  '# `varieties[v].status` — `attested` if some entry\'s reading in variety `v`',
  '# uses this syllable (see `attested_entries`), else `unattested`. Only',
  '# readings count, not example-sentence Peng\'im (examples carry no `variety`).',
  '#',
  "# `external` — whether an independent published chart (currently just",
  "# learnteochew.com, see data/phonology/external/) corroborates this",
  "# syllable's rime, regardless of lexicon attestation. unattested +",
  "# external: true reads as 'probably real, just needs a headword';",
  "# unattested + external: false reads as 'possibly one of the",
  "# combinatorial gaps the grammar over-generates.'",
  '#',
  `# NOTE: only one entry in the whole lexicon has an explicit non-Chaozhou`,
  `# reading. So ${onlyShantouChaoyang.join('/')} below show almost total`,
  '# `unattested` — an honest reflection of current data, not a generator bug.',
  '# See data/phonology/REVIEW.md § 10.',
  '',
].join('\n')

mkdirSync(WORDLISTS_DIR, { recursive: true })
writeFileSync(SYLLABLE_INVENTORY_FILE, header + stringify(inventory))

console.log(`${inventory.items.length} syllables → ${SYLLABLE_INVENTORY_FILE}`)
for (const v of inventory.varieties) console.log(`  ${v}: ${unattestedCounts[v]} unattested`)
