import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { parse as parseYaml, stringify } from 'yaml'

import { WIKTIONARY_WORDLIST_FILE, WORDLISTS_DIR } from '../paths.js'
import type { LoadedEntry } from './load.js'

/**
 * `data/wordlists/wiktionary-teochew-index.yaml` — the checklist for issue
 * #54, tracking every Wiktionary page enumerated by
 * `searchTeochewPages` (`../importers/wiktionary-search.js`) against the
 * lexicon. Same `status` lifecycle as `swadesh-207.yaml`, but unlike that
 * hand-maintained list, this file is regenerated by
 * `npm run wordlist:wiktionary` and updated in place by
 * `npm run import -- wiktionary --from-wordlist`.
 */

export type WiktionaryWordlistStatus = 'existing' | 'to_fetch' | 'staged' | 'no_reading' | 'no_gloss'

export interface WiktionaryWordlistItem {
  headword: string
  status: WiktionaryWordlistStatus
  /** Present when `status` is `existing`; the matching data/entries/ id. */
  entry_id?: string
}

export interface WiktionaryWordlist {
  list: string
  items: WiktionaryWordlistItem[]
}

const HEADER = [
  '# Wiktionary Teochew index (issue #54) — every Wiktionary page whose wikitext',
  '# declares a Teochew reading (`insource:/mn-t=/`, namespace 0), enumerated via',
  '# CirrusSearch rather than guessed from a frequency list (see issue #53,',
  '# superseded). Unlike swadesh-207.yaml, `headword` needs no manual curation —',
  '# the Wiktionary page title already IS the headword on record there.',
  '#',
  '# `status` lifecycle (same as swadesh-207.yaml):',
  '#   existing    - already a headword (or variant) in data/entries/ (see entry_id)',
  '#   to_fetch    - not yet run through the importer',
  '#   staged      - importer produced a proposal in data/staging/wiktionary.yaml',
  '#   no_reading  - importer found no usable Teochew reading (see the `misses`',
  '#                 list in data/staging/wiktionary.yaml)',
  '#   no_gloss    - has a staged reading, but a human/agent hand-checked its',
  '#                 live Wiktionary page (issue #68 batch 20) and confirmed it',
  '#                 gives no independently definable gloss (bound character,',
  '#                 compound-only note, or unfilled rfdef stub) — a terminal,',
  '#                 not-actionable state, distinct from `staged`',
  '#',
  '# Regenerated by `npm run wordlist:wiktionary` (re-enumerates + re-checks',
  '# against data/entries/) and updated in place by',
  '# `npm run import -- wiktionary --from-wordlist` (flips to_fetch items to',
  '# staged/no_reading as they are processed). Regeneration preserves any',
  '# staged/no_reading/no_gloss status already recorded — it never resets progress.',
  '',
].join('\n')

export function loadWiktionaryWordlist(): WiktionaryWordlist | null {
  if (!existsSync(WIKTIONARY_WORDLIST_FILE)) return null
  return parseYaml(readFileSync(WIKTIONARY_WORDLIST_FILE, 'utf8')) as WiktionaryWordlist
}

export function writeWiktionaryWordlist(items: WiktionaryWordlistItem[]): void {
  mkdirSync(WORDLISTS_DIR, { recursive: true })
  const data: WiktionaryWordlist = { list: 'wiktionary-teochew-index', items }
  writeFileSync(WIKTIONARY_WORDLIST_FILE, HEADER + stringify(data))
}

/**
 * Classifies candidate Wiktionary page titles against the current lexicon.
 * A title already in `previous` as `staged`/`no_reading`/`no_gloss` keeps that
 * status — regeneration must not erase import progress just because the live
 * search was rerun.
 */
export function classifyAgainstEntries(
  titles: string[],
  entries: LoadedEntry[],
  previous?: WiktionaryWordlist | null,
): WiktionaryWordlistItem[] {
  const entryIdByHeadword = new Map<string, string>()
  for (const { entry } of entries) {
    entryIdByHeadword.set(entry.headword, entry.id)
    for (const variant of entry.variants ?? []) entryIdByHeadword.set(variant, entry.id)
  }

  const previousByHeadword = new Map<string, WiktionaryWordlistItem>()
  for (const item of previous?.items ?? []) previousByHeadword.set(item.headword, item)

  return titles.map((headword) => {
    const entryId = entryIdByHeadword.get(headword)
    if (entryId) return { headword, status: 'existing', entry_id: entryId }

    const prior = previousByHeadword.get(headword)
    if (prior?.status === 'staged' || prior?.status === 'no_reading' || prior?.status === 'no_gloss') {
      return { headword, status: prior.status }
    }

    return { headword, status: 'to_fetch' }
  })
}
